//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MHEntities : DbContext
    {
        public MHEntities()
            : base("name=MHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
        public virtual DbSet<OgrenciNetWork> OgrenciNetWork { get; set; }
        public virtual DbSet<OgrenciProfil> OgrenciProfil { get; set; }
        public virtual DbSet<VW_Ogrenci_Network> VW_Ogrenci_Network { get; set; }
    }
}
