//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Context
{
    using System;
    using System.Collections.Generic;

    public partial class VW_Ogrenci_Network
    {
        public int id { get; set; }
        public long No { get; set; }
        public string AdSoyad { get; set; }
        public string Network { get; set; }
        public string Cevap { get; set; }
        public int Label { get; set; }
        public double Puan { get; set; }
    }
}
